name: keyviz
description: visualize your keypress and mouse actions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # cross-platform HID (Human Input Device) listener
  hid_listener:
    git:
      url: https://github.com/localcc/hid_listener.git
      ref: main

    version: ^1.1.2

  tuple: ^2.0.2
  provider: ^6.0.5
  flutter_svg: ^2.0.7
  vector_math: ^2.1.4
  # tray_manager: ^0.2.0
  window_manager: ^0.3.4
  flutter_acrylic: ^1.1.3
  screen_retriever: ^0.1.6
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 900